# -*- coding: utf-8 -*-
"""SVM.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8EUtbsZoT_Vb9vy4FGPMCsOcTpz0mNi
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report

data={"Age":[30,25,35,20,40,55,32,38],"Monthly_Charge":[50,60,80,40,100,120,70,55],"churn":[1,0,1,0,1,0,1,0]}
datapd=pd.DataFrame(data)

print(datapd)

y=datapd["churn"]
print(y)

x=datapd[["Age","Monthly_Charge"]]



x

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

model=SVC(kernel='linear',C=1.0)

model.fit(xtrain,ytrain)

pred=model.predict(xtest)
ac=accuracy_score(ytest,pred)

print(ac)

userage=int(input("Enter the data:"))
userm=int(input("Enter the monthly charges:"))
userdata=np.array([[userage,userm]])
ans=model.predict(userdata)
if(ans[0]==1):
  print("Churned")
else:
  print("Not Churned")

